apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeemanageravecjenkins
spec:
  selector:
    matchLabels:
      app: employeemanageravecjenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: employeemanageravecjenkins
    spec:
      containers:
        - name: jenkins
          image: farahhachicha/devops-integration
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: employee
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: Farah@99
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service-avecjenkins
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort:   # Port exposed to the outside
  selector:
    app: employeemanageravecjenkins
  type: NodePort
